### ISSUE TITLE
'__startswith' filter

### ISSUE THREAD

**Issue by rossigee** [encode/orm#49]
This would be very useful in our project.

**Comment by malikoth** [comment]
What about also support for `istartswith`, `endswith`, and `iendswith`?

**Comment by collerek** [comment]
Hi,

This project seems stale and from what I saw on encode page it's not a priority right now. Since I was tired with reinventing the wheel and needed something as soon as possible I created ormar package, that was inspired by this one. 

Ormar bases its validation on pydantic so it can be used directly with fastapi as response and request models.

This issue was implemented in ormar, so feel free to check it  out: https://github.com/collerek/ormar

**Comment by aminalaee** [comment]
This can be achieved using SQLAlchemy filters now.
