### ISSUE TITLE
How to make pagination on ORM Package?

### ISSUE THREAD

**Issue by MarcusMann** [encode/orm#52]
Hi, Guys!

I'm with a question about how to make pagination as orm package? I see that exist a issue #30  add the offset, however, this is not completed merge.

Thanks

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀

**Comment by tomchristie** [comment]
Hi there, thanks for getting involved. 😃

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
