### ISSUE TITLE
Add QuerySet-level method: bulk_create

### ISSUE THREAD

**Issue by malikoth** [encode/orm#55]
I need an efficient way to add records to a db in bulk.  I don't think it matters so much what the API looks like for accomplishing that.  If there is an efficient way to do that already, even if it's not a QS-level method, please let me know.

Reference:  https://docs.djangoproject.com/en/3.0/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create

**Comment by rrmerugu** [comment]
+1 . any update on this ?

**Comment by asnelling** [comment]
Tackling it now

**Comment by collerek** [comment]
Hi,

This project seems stale and from what I saw on encode page it's not a priority right now. Since I was tired with reinventing the wheel and needed something as soon as possible I created ormar package, that was inspired by this one. 

Ormar bases its validation on pydantic so it can be used directly with fastapi as response and request models.

This issue was implemented in ormar, so feel free to check it  out: https://github.com/collerek/ormar

**Comment by dlo** [comment]
This has been fixed with https://github.com/encode/orm/commit/0df624ef88616f0ae5d4a96a60f79c43b79f130f, so probably should be closed. cc/ @aminalaee
