### ISSUE TITLE
Is there a way to support alternate column names?

### ISSUE THREAD

**Issue by n8henrie** [encode/orm#75]
I have a table that I'm trying to adapt from sqlalchemy in which a column name is a Python keyword (`open`). In my sqlalchemy table, I use `open_ = Column("open", Float)` so as to avoid overriding the keyword.

In my `orm.Model`, I'm unable to find a way to have an equivalent mapping of the `mymodel.open_` object.

I tried `open_ = orm.Float(name="open")` but that isn't a supported kwarg.

`open_ = orm.Float(title="open")` doesn't work, resulting in `asyncpg.exceptions.UndefinedColumnError: column tiingo_daily_historical.open_`

Am I overlooking a way to do this?

Many thanks in advance!

[0]: https://docs.sqlalchemy.org/en/13/core/metadata.html#sqlalchemy.schema.Column

**Comment by collerek** [comment]
Hi,

This project seems stale and from what I saw on encode page it's not a priority right now. Since I was tired with reinventing the wheel and needed something as soon as possible I created ormar package, that was inspired by this one. 

Ormar bases its validation on pydantic so it can be used directly with fastapi as response and request models.

This issue was implemented in ormar, so feel free to check it  out: https://github.com/collerek/ormar

**Comment by aminalaee** [comment]
With or version 2 this is possible:

```python
class Note(orm.Model):
    tablename = "notes"
    registry = models
    fields = {
        "id": orm.Integer(primary_key=True),
        "text": orm.String(max_length=100),
        "completed": orm.Boolean(default=False),
    }
```
